// ─────────────────────────────────────────────────────────────────
// generatePptx.ts  —  client-side PPTX generation for Refract
// Uses PptxGenJS v3 (browser mode). Import dynamically from page.tsx.
// ─────────────────────────────────────────────────────────────────

export type ContentDeckData = {
  businessName: string;
  businessType: string;
  campaignGoal: string;
  contentType: string;
  tone: string;
  output: {
    instagram: string;
    facebook: string;
    whatsapp: string;
    email: string;
    linkedin: string;
  };
};

// ── Palette ───────────────────────────────────────────────────────
const C = {
  bg:           "07071a",
  surface:      "0d0d24",
  surfaceLight: "12122e",
  violet:       "8b5cf6",
  violetDark:   "4c1d95",
  fuchsia:      "d946ef",
  white:        "FFFFFF",
  muted:        "8888aa",
  dim:          "4b4b6a",
  // platform accents
  instagram:    "e11d48",
  facebook:     "3b82f6",
  whatsapp:     "10b981",
  email:        "f59e0b",
  linkedin:     "0ea5e9",
} as const;

const PLATFORM_META = [
  { key: "instagram",  label: "Instagram",         color: C.instagram },
  { key: "facebook",   label: "Facebook",           color: C.facebook  },
  { key: "whatsapp",   label: "WhatsApp",           color: C.whatsapp  },
  { key: "email",      label: "Email Newsletter",   color: C.email     },
  { key: "linkedin",   label: "LinkedIn",           color: C.linkedin  },
] as const;

// ── Helpers ───────────────────────────────────────────────────────

/** Left violet accent bar used on every slide */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addAccentBar(slide: any, color: string = C.violet) {
  slide.addShape("rect", {
    x: 0, y: 0, w: 0.16, h: 5.625,
    fill: { color },
    line: { color, width: 0 },
  });
}

/** Slim footer line */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addFooter(slide: any, label: string) {
  slide.addText(label, {
    x: 0.3, y: 5.3, w: 9.4, h: 0.22,
    fontSize: 8,
    color: C.dim,
    align: "right",
    margin: 0,
  });
}

/** Surface card rectangle */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addCard(slide: any, x: number, y: number, w: number, h: number, color: string = C.surface) {
  slide.addShape("rect", {
    x, y, w, h,
    fill: { color },
    line: { color: "1a1a35", width: 1 },
  });
}

// ── Main export ───────────────────────────────────────────────────

export async function generateContentDeck(data: ContentDeckData): Promise<void> {
  // Dynamic import keeps the library out of the SSR bundle
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const PptxGenJS = ((await import("pptxgenjs")) as any).default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pres: any = new PptxGenJS();

  pres.layout  = "LAYOUT_16x9";
  pres.author  = "Refract";
  pres.company = "Refract — Powered by Claude AI";
  pres.title   = `${data.businessName} — Content Strategy Deck`;

  const dateStr = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "short", year: "numeric",
  });

  // ── Slide 1: Cover ─────────────────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: C.bg };
    addAccentBar(s, C.violet);

    // "REFRACT" watermark top-right
    s.addText("REFRACT", {
      x: 7.8, y: 0.28, w: 2, h: 0.35,
      fontSize: 9, bold: true, charSpacing: 5,
      color: C.dim, align: "right", margin: 0,
    });

    // Business name
    s.addText(data.businessName || "Your Business", {
      x: 0.5, y: 1.55, w: 9, h: 1.0,
      fontSize: 40, bold: true,
      color: C.white, align: "left", margin: 0,
    });

    // Deck type
    s.addText("Content Strategy Deck", {
      x: 0.5, y: 2.65, w: 9, h: 0.5,
      fontSize: 18,
      color: C.violet, align: "left", margin: 0,
    });

    // Divider
    s.addShape("rect", {
      x: 0.5, y: 3.3, w: 2.8, h: 0.03,
      fill: { color: C.violetDark },
      line: { color: C.violetDark, width: 0 },
    });

    // Campaign goal
    s.addText(`Campaign Goal: ${data.campaignGoal}`, {
      x: 0.5, y: 3.5, w: 9, h: 0.4,
      fontSize: 13,
      color: C.muted, align: "left", margin: 0,
    });

    // Date
    s.addText(dateStr, {
      x: 0.5, y: 4.0, w: 9, h: 0.3,
      fontSize: 11,
      color: C.dim, align: "left", margin: 0,
    });

    addFooter(s, "Generated by Refract · Powered by Claude AI");
  }

  // ── Slide 2: Campaign Overview ─────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: C.bg };
    addAccentBar(s);

    s.addText("Campaign Overview", {
      x: 0.4, y: 0.35, w: 9, h: 0.55,
      fontSize: 22, bold: true,
      color: C.white, margin: 0,
    });

    // Left details card
    addCard(s, 0.4, 1.05, 4.2, 3.8);
    const details = [
      { label: "Business",      value: data.businessName || "—" },
      { label: "Type",          value: data.businessType },
      { label: "Content Type",  value: data.contentType },
      { label: "Tone",          value: data.tone },
      { label: "Campaign Goal", value: data.campaignGoal },
    ];
    details.forEach((d, i) => {
      const rowY = 1.2 + i * 0.7;
      s.addText(d.label.toUpperCase(), {
        x: 0.6, y: rowY, w: 3.8, h: 0.25,
        fontSize: 9, bold: true, charSpacing: 1,
        color: C.dim, margin: 0,
      });
      s.addText(d.value, {
        x: 0.6, y: rowY + 0.26, w: 3.8, h: 0.3,
        fontSize: 13, bold: false,
        color: C.white, margin: 0,
      });
    });

    // Right platforms card
    addCard(s, 5.0, 1.05, 4.6, 3.8);
    s.addText("5 Platform Posts Ready", {
      x: 5.15, y: 1.2, w: 4.3, h: 0.35,
      fontSize: 11, bold: true,
      color: C.violet, margin: 0,
    });

    PLATFORM_META.forEach((p, i) => {
      const py = 1.75 + i * 0.6;
      // Color dot
      s.addShape("ellipse", {
        x: 5.15, y: py + 0.04, w: 0.18, h: 0.18,
        fill: { color: p.color },
        line: { color: p.color, width: 0 },
      });
      s.addText(p.label, {
        x: 5.45, y: py, w: 4.0, h: 0.28,
        fontSize: 13,
        color: C.white, margin: 0,
      });
    });

    addFooter(s, `${data.businessName} · Refract Content Deck · ${dateStr}`);
  }

  // ── Slides 3–7: Platform slides ────────────────────────────────
  PLATFORM_META.forEach((platform) => {
    const copy = data.output[platform.key as keyof typeof data.output];
    const s = pres.addSlide();
    s.background = { color: C.bg };

    // Platform-coloured left accent bar
    addAccentBar(s, platform.color);

    // Platform name
    s.addText(platform.label.toUpperCase(), {
      x: 0.35, y: 0.3, w: 5, h: 0.5,
      fontSize: 20, bold: true, charSpacing: 2,
      color: platform.color, margin: 0,
    });

    // "Platform post" label
    s.addText("Platform Post", {
      x: 0.35, y: 0.82, w: 5, h: 0.28,
      fontSize: 10,
      color: C.dim, margin: 0,
    });

    // Char count badge (top right)
    s.addText(`${copy.length} characters`, {
      x: 7.2, y: 0.38, w: 2.5, h: 0.3,
      fontSize: 10,
      color: C.muted, align: "right", margin: 0,
    });

    // Content card
    addCard(s, 0.35, 1.2, 9.3, 3.6, C.surfaceLight);

    // Left colour accent strip inside card
    s.addShape("rect", {
      x: 0.35, y: 1.2, w: 0.06, h: 3.6,
      fill: { color: platform.color },
      line: { color: platform.color, width: 0 },
    });

    // Copy text
    s.addText(copy, {
      x: 0.6, y: 1.3, w: 8.9, h: 3.4,
      fontSize: 12.5,
      color: C.white,
      align: "left",
      valign: "top",
      wrap: true,
      margin: [0.1, 0.15, 0.1, 0.15],
    });

    addFooter(s, `${data.businessName} · ${platform.label} · Refract Content Deck · ${dateStr}`);
  });

  // ── Slide 8: Next Steps ────────────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: C.bg };
    addAccentBar(s, C.fuchsia);

    // Top accent band
    s.addShape("rect", {
      x: 0, y: 0, w: 10, h: 1.0,
      fill: { color: C.violetDark },
      line: { color: C.violetDark, width: 0 },
    });

    s.addText("You're ready to post.", {
      x: 0.35, y: 0.22, w: 9, h: 0.55,
      fontSize: 22, bold: true,
      color: C.white, margin: 0,
    });

    s.addText(
      `This deck was generated from a single content input using Refract + Claude AI.\nReview each platform post, make any edits, then post.`,
      {
        x: 0.35, y: 1.15, w: 9, h: 0.65,
        fontSize: 12,
        color: C.muted, margin: 0,
      }
    );

    // Checklist
    const checks = PLATFORM_META.map((p) => `Review & post: ${p.label}`);
    s.addText(
      checks.map((text, i) => ({
        text,
        options: {
          bullet: true,
          breakLine: i < checks.length - 1,
          color: C.white,
          fontSize: 13,
        },
      })),
      { x: 0.5, y: 2.0, w: 8.5, h: 2.6 }
    );

    addFooter(s, "Generated by Refract · Powered by Claude AI · refract.app");
  }

  // ── Write the file ─────────────────────────────────────────────
  const safeName = (data.businessName || "Refract")
    .replace(/[^a-z0-9]/gi, "-")
    .toLowerCase();

  await pres.writeFile({
    fileName: `${safeName}-content-deck-${dateStr.replace(/\s/g, "-")}.pptx`,
  });
}
